### Create a new patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Kafka1",
  "email": "kafka_test1@example.com",
  "address": "123 Java Street",
  "dateOfBirth": "2003-03-21",
  "registeredDate": "2025-06-25"
}
